name:                parconc-playground
version:             0.1.0.0
github:              "githubuser/parconc-playground"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/parconc-playground#readme>

dependencies:
- base     >= 4.7 && < 5
- parallel == 3.2.2.0
- array    == 0.5.3.0
- HTTP     == 4000.3.12
- time     == 1.8.0.2
- stm      == 2.5.0.0

library:
  source-dirs: src

executables:
  parconc-playground-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    # - -with-rtsopts=-N
    dependencies:
    - parconc-playground

tests:
  parconc-playground-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -eventlog
    # - -with-rtsopts=-N
    dependencies:
    - parconc-playground
